### ISSUE TITLE
Test run failed at map_genome: "[gzclose] buffer error"

### ISSUE THREAD

**Issue by jmpolinski** [Nextomics/NextPolish#117]
I just installed NextPolish but am getting errors when I try to run the test data that results in "map_genome failed". The final line in the nextPolinski.sh.e files is "[gzclose] buffer error"

**Error message**
[83702 INFO] 2023-07-26 18:37:04 Submitted jobID:[83870] jobCmd:[/data/app/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome1/nextPolish.sh] in the local_cycle.
[83870 CRITICAL] 2023-07-26 18:37:04 Command '/bin/bash /data/app/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome1/nextPolish.sh > /data/app/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome1/nextPolish.sh.o 2> /data/app/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome1/nextPolish.sh.e' returned non-zero exit status 1, error info: .
Traceback (most recent call last):
  File "./nextPolish", line 515, in <module>
    main(args)
  File "./nextPolish", line 412, in main
    task.run.start()
  File "/usr/lib/python2.7/site-packages/paralleltask/task_control.py", line 350, in start
    self._start()
  File "/usr/lib/python2.7/site-packages/paralleltask/task_control.py", line 374, in _start
    self.submit(job)
  File "/usr/lib/python2.7/site-packages/paralleltask/task_control.py", line 254, in submit
    _, stdout, _ = self.run(job.cmd)
  File "/usr/lib/python2.7/site-packages/paralleltask/task_control.py", line 294, in run
    log.critical("Command '%s' returned non-zero exit status %d, error info: %s." % (cmd, p.returncode, stderr))
  File "/usr/lib64/python2.7/logging/__init__.py", line 1194, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1268, in _log
    self.handle(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1278, in handle
    self.callHandlers(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1318, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/p
[map-genome1_nextPolish.sh.e.txt](https://github.com/Nextomics/NextPolish/files/12177902/map-genome1_nextPolish.sh.e.txt)
[map-genome2_nextPolish.sh.e.txt](https://github.com/Nextomics/NextPolish/files/12177903/map-genome2_nextPolish.sh.e.txt)
ython2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/lib/python2.7/site-packages/paralleltask/kit.py", line 42, in emit
    raise Exception(record.msg)
Exception: Command '/bin/bash /data/app/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome1/nextPolish.sh > /data/app/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome1/nextPolish.sh.o 2> /data/app/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome1/nextPolish.sh.e' returned non-zero exit status 1, error info: .
[83702 INFO] 2023-07-26 18:37:04 Submitted jobID:[83916] jobCmd:[/data/app/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome2/nextPolish.sh] in the local_cycle.
[83916 CRITICAL] 2023-07-26 18:37:04 Command '/bin/bash /data/app/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome2/nextPolish.sh > /data/app/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome2/nextPolish.sh.o 2> /data/app/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome2/nextPolish.sh.e' returned non-zero exit status 1, error info: .
Traceback (most recent call last):
  File "./nextPolish", line 515, in <module>
    main(args)
  File "./nextPolish", line 412, in main
    task.run.start()
  File "/usr/lib/python2.7/site-packages/paralleltask/task_control.py", line 350, in start
    self._start()
  File "/usr/lib/python2.7/site-packages/paralleltask/task_control.py", line 374, in _start
    self.submit(job)
  File "/usr/lib/python2.7/site-packages/paralleltask/task_control.py", line 254, in submit
    _, stdout, _ = self.run(job.cmd)
  File "/usr/lib/python2.7/site-packages/paralleltask/task_control.py", line 294, in run
    log.critical("Command '%s' returned non-zero exit status %d, error info: %s." % (cmd, p.returncode, stderr))
  File "/usr/lib64/python2.7/logging/__init__.py", line 1194, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1268, in _log
    self.handle(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1278, in handle
    self.callHandlers(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1318, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/lib/python2.7/site-packages/paralleltask/kit.py", line 42, in emit
    raise Exception(record.msg)
Exception: Command '/bin/bash /data/app/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome2/nextPolish.sh > /data/app/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome2/nextPolish.sh.o 2> /data/app/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome2/nextPolish.sh.e' returned non-zero exit status 1, error info: .
[83702 ERROR] 2023-07-26 18:37:10 map_genome failed: please check the following logs:
[83702 ERROR] 2023-07-26 18:37:10 /data/app/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome1/nextPolish.sh.e
[83702 ERROR] 2023-07-26 18:37:10 /data/app/NextPolish/test_data/01_rundir/01.score_chain/03.map.ref.sh.work/map_genome2/nextPolish.sh.e

**Operating system**
RHEL7 

**GCC**
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Python**
Tried it with both 3.8.12 and 2.7.5

**NextPolish**
v1.4.1

**Comment by moold** [comment]
This error should be caused by `bwa` or `minimap2`, see [here](https://www.biostars.org/p/248223/) and check your fastq files are not truncated or corrupted.

**Comment by jmpolinski** [comment]
These are the test data - are there md5 checksums I can use to check if these files downloaded properly?

**Comment by moold** [comment]
Yes, see below:
```
ddc32d12b77d07488a325370a50bdbf6  hifi.fasta.gz
e7c9868ea938569b208d02d4f6e86c4c  lreads.fasta.gz
3fca064388790538b76b0bfaeeaddcad  raw.genome.fasta
840bc495b6d53a672d9495876845134c  run.cfg
e639a109d3451c090d3ef34ba9078ed2  sgs.fofn
be8c7851865819971fb3a5bb9a371fd9  sreads.R1.fastq.gz
65b12a65c7324688747973c2fb88c640  sreads.R2.fastq.gz
```
I can't reproduce the error you mentioned, so I think you can check that these data are complete and try again with default parameters.
