### ISSUE TITLE
db_split failed:

### ISSUE THREAD

**Issue by YDD99** [Nextomics/NextPolish#119]
"/home/xly/soft/NextPolish/nextPolish" run.cfg
[1941029 INFO] 2023-08-16 13:07:01 NextPolish start...
[1941029 INFO] 2023-08-16 13:07:01 version:v1.4.1 logfile:pid1941029.log.info
[1941029 WARNING] 2023-08-16 13:07:01 Re-write workdir
[1941029 WARNING] 2023-08-16 13:07:01 Delete task: 5 due to missing lgs_fofn.
[1941029 WARNING] 2023-08-16 13:07:01 Delete task: 5 due to missing lgs_fofn.
[1941029 WARNING] 2023-08-16 13:07:01 Delete task: 6 due to missing hifi_fofn.
[1941029 WARNING] 2023-08-16 13:07:01 Delete task: 6 due to missing hifi_fofn.
[1941029 INFO] 2023-08-16 13:07:01 scheduled tasks:
[1, 2, 1, 2]
[1941029 INFO] 2023-08-16 13:07:01 options:
[1941029 INFO] 2023-08-16 13:07:01
rerun:                        3
rewrite:                      1
kill:                         None
cleantmp:                     0
use_drmaa:                    0
submit:                       None
deltmp:                       False
job_type:                     local
sgs_unpaired:                 0
sgs_rm_nread:                 1
lgs_read_type:
parallel_jobs:                5
align_threads:                2
check_alive:                  None
task:                         [1, 2, 1, 2]
job_id_regex:                 None
sgs_max_depth:                100
lgs_max_depth:                100
multithread_jobs:             2
lgs_max_read_len:             0
hifi_max_depth:               100
polish_options:               -p 2
lgs_block_size:               500M
lgs_min_read_len:             1k
hifi_max_read_len:            0
genome_size:                  44463965
hifi_block_size:              500M
hifi_min_read_len:            1k
job_prefix:                   nextPolish
sgs_block_size:               500000000
sgs_use_duplicate_reads:      0
lgs_minimap2_options:         -x map-ont
hifi_minimap2_options:        -x map-pb
sgs_align_options:            bwa mem -p  -t 2
workdir:                      /home/xly/work8/313/finalfasta/./rundir
sgs_fofn:                     /home/xly/work8/313/finalfasta/sgs.fofn
genome:                       /home/xly/work8/313/finalfasta/WYBBLT7.final.fasta
snp_phase:                    /home/xly/work8/313/finalfasta/./rundir/%02d.snp_phase
snp_valid:                    /home/xly/work8/313/finalfasta/./rundir/%02d.snp_valid
lgs_polish:                   /home/xly/work8/313/finalfasta/./rundir/%02d.lgs_polish
kmer_count:                   /home/xly/work8/313/finalfasta/./rundir/%02d.kmer_count
hifi_polish:                  /home/xly/work8/313/finalfasta/./rundir/%02d.hifi_polish
score_chain:                  /home/xly/work8/313/finalfasta/./rundir/%02d.score_chain
[1941029 INFO] 2023-08-16 13:07:01 step 0 and task 1 start:
[1941029 INFO] 2023-08-16 13:07:06 Total jobs: 3
[1941029 INFO] 2023-08-16 13:07:06 Submitted jobID:[1941100] jobCmd:[/home/xly/work8/313/finalfasta/rundir/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh] in the local_cycle.
[1941100 CRITICAL] 2023-08-16 13:07:06 Command '/bin/bash /home/xly/work8/313/finalfasta/rundir/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh > /home/xly/work8/313/finalfasta/rundir/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh.o 2> /home/xly/work8/313/finalfasta/rundir/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh.e' returned non-zero exit status 1, error info: .
Traceback (most recent call last):
  File "/home/xly/soft/NextPolish/nextPolish", line 553, in <module>
    main(args)
  File "/home/xly/soft/NextPolish/nextPolish", line 403, in main
    task.run.start()
  File "/home/xly/mambaforge/lib/python3.10/site-packages/paralleltask/task_control.py", line 350, in start
    self._start()
  File "/home/xly/mambaforge/lib/python3.10/site-packages/paralleltask/task_control.py", line 374, in _start
    self.submit(job)
  File "/home/xly/mambaforge/lib/python3.10/site-packages/paralleltask/task_control.py", line 254, in submit
    _, stdout, _ = self.run(job.cmd)
  File "/home/xly/mambaforge/lib/python3.10/site-packages/paralleltask/task_control.py", line 294, in run
    log.critical("Command '%s' returned non-zero exit status %d, error info: %s." % (cmd, p.returncode, stderr))
  File "/home/xly/mambaforge/lib/python3.10/logging/__init__.py", line 1524, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/home/xly/mambaforge/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/home/xly/mambaforge/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/home/xly/mambaforge/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/home/xly/mambaforge/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/home/xly/mambaforge/lib/python3.10/site-packages/paralleltask/kit.py", line 42, in emit
    raise Exception(record.msg)
Exception: Command '/bin/bash /home/xly/work8/313/finalfasta/rundir/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh > /home/xly/work8/313/finalfasta/rundir/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh.o 2> /home/xly/work8/313/finalfasta/rundir/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh.e' returned non-zero exit status 1, error info: .
[1941029 INFO] 2023-08-16 13:07:07 Submitted jobID:[1941106] jobCmd:[/home/xly/work8/313/finalfasta/rundir/00.score_chain/01.db_split.sh.work/db_split2/nextPolish.sh] in the local_cycle.
[1941029 INFO] 2023-08-16 13:07:07 Submitted jobID:[1941112] jobCmd:[/home/xly/work8/313/finalfasta/rundir/00.score_chain/01.db_split.sh.work/db_split3/nextPolish.sh] in the local_cycle.
[1941029 ERROR] 2023-08-16 13:08:11 db_split failed: please check the following logs:
[1941029 ERROR] 2023-08-16 13:08:11 /home/xly/work8/313/finalfasta/rundir/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh.e

**Comment by YDD99** [comment]
run.cfg
[General]
job_type = local
job_prefix = nextPolish
task = best
rewrite = yes
rerun = 3
parallel_jobs = 5
multithread_jobs = 2
genome = /home/xly/work8/313/finalfasta/WYBBLT7.final.fasta #genome file
genome_size = auto
workdir = ./rundir
polish_options = -p {multithread_jobs}

[sgs_option]
sgs_fofn = /home/xly/work8/313/finalfasta/sgs.fofn
sgs_options = -max_depth 100 -bwa

sgs.fofn
/home/xly/work8/313/WYBBLT7/WYBBLT7_1.clean.fq.gz
/home/xly/work8/313/WYBBLT7/WYBBLT7_2.clean.fq.gz

**Comment by YDD99** [comment]
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.5.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-5Q4PKF/gcc-9-9.5.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
gcc version 9.5.0 (Ubuntu 9.5.0-1ubuntu1~22.04)

python --version
Python 3.10.10

**Comment by moold** [comment]
Could you paste the content of file `/home/xly/work8/313/finalfasta/rundir/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh.e` to here?

**Comment by ian-ariel** [comment]
> Could you paste the content of file `/home/xly/work8/313/finalfasta/rundir/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh.e` to here?

take a look at mine, please. Had the same issue. My system is in portuguese, though


hostname
+ hostname
cd /home/engebiozero/ian/IanBac-20240614T173351Z-001/IanBac/barcode01/polish/00.lgs_polish/01.db_split.sh.work/db_split1
+ cd /home/engebiozero/ian/IanBac-20240614T173351Z-001/IanBac/barcode01/polish/00.lgs_polish/01.db_split.sh.work/db_split1
( time  /home/engebiozero/ian/NextPolish/bin/seq_split -d /home/engebiozero/ian/IanBac-20240614T173351Z-001/IanBac/barcode01/polish -m 185000000.0 -n 2 -i 0 -t 3 -f 5k -l 0 -s 370000000 -p input.lgspart /home/engebiozero/ian/IanBac-20240614T173351Z-001/IanBac/barcode01/polish/lgs.fofn )
+ /home/engebiozero/ian/NextPolish/bin/seq_split -d /home/engebiozero/ian/IanBac-20240614T173351Z-001/IanBac/barcode01/polish -m 185000000.0 -n 2 -i 0 -t 3 -f 5k -l 0 -s 370000000 -p input.lgspart /home/engebiozero/ian/IanBac-20240614T173351Z-001/IanBac/barcode01/polish/lgs.fofn
/home/engebiozero/ian/IanBac-20240614T173351Z-001/IanBac/barcode01/polish/00.lgs_polish/01.db_split.sh.work/db_split1/bar1sup_nextdenovo.sh: linha 5: /home/engebiozero/ian/NextPolish/bin/seq_split: Arquivo ou diretório inexistente  #TRANSLATION File or directory don't exist

real	0m0,001s
user	0m0,001s
sys	0m0,000s
