### ISSUE TITLE
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

### ISSUE THREAD

**Issue by berombau** [Nextomics/NextPolish#13]
Running nextPolish v1.0.5

Execution of nextPolish
```
(base) berombau@agro:/data/dp1/public/output/nextpolish$ nextPolish run.cfg                                          
[INFO] 2019-12-08 20:45:12,272 start...                                                                              
[INFO] 2019-12-08 20:45:12,308 logfile: pid29840.log.info                                                            
[WARNING] 2019-12-08 20:45:12,309 Re-write workdir                                                                   
[INFO] 2019-12-08 20:45:12,309 scheduled tasks:                                                                      
[1, 2, 1, 2]                                                                                                         
[INFO] 2019-12-08 20:45:12,309 options:                                                                              
[INFO] 2019-12-08 20:45:12,309 {'polish_options': '-p 2', 'rewrite': 1, 'job_prefix': 'nextPolish', 'job_type': 'loca
l', 'cluster_options': '', 'snp_valid': '/data/dp1/public/output/nextpolish/./01_rundir/%02d.snp_valid', 'kmer_count'
: '/data/dp1/public/output/nextpolish/./01_rundir/%02d.kmer_count', 'lgs_fofn': 0, 'sgs_max_depth': '100', 'sgs_block
_size': 500000000, 'lgs_max_read_len': '150k', 'parallel_jobs': '10', 'multithread_jobs': '2', 'snp_phase': '/data/dp
1/public/output/nextpolish/./01_rundir/%02d.snp_phase', 'genome': '/data/dp1/public/output/medaka/consensus.fasta', '
genome_size': 300000000, 'workdir': '/data/dp1/public/output/nextpolish/./01_rundir', 'cleantmp': 0, 'sgs_align_optio
ns': 'minimap2 --split-prefix tmp -a -x sr -t 2', 'sgs_unpaired': '0', 'sgs_fofn': '/data/dp1/public/output/nextpolis
h/sgs.fofn', 'align_threads': '2', 'sgs_use_duplicate_reads': 0, 'score_chain': '/data/dp1/public/output/nextpolish/.
/01_rundir/%02d.score_chain', 'task': [1, 2, 1, 2], 'lgs_max_depth': '60', 'lgs_block_size': '500M', 'lgs_minimap2_op
tions': '-x map-ont', 'rerun': 3, 'lgs_min_read_len': '1k'}                                                          
[INFO] 2019-12-08 20:45:12,309 step 0 and task 1 start:                                                              
[INFO] 2019-12-08 20:45:12,310 analysis tasks done                                                                   
[INFO] 2019-12-08 20:45:12,311 total jobs: 3                                                                         
[INFO] 2019-12-08 20:45:12,312 Throw jobID:[29841] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chai
n/01.db_split.sh.work/db_split0/nextPolish.sh] in the local_cycle.                                                   
[INFO] 2019-12-08 20:45:12,814 Throw jobID:[29849] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chai
n/01.db_split.sh.work/db_split1/nextPolish.sh] in the local_cycle.                                                   
[INFO] 2019-12-08 20:45:13,316 Throw jobID:[29858] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chai
n/01.db_split.sh.work/db_split2/nextPolish.sh] in the local_cycle.                                                   
[INFO] 2019-12-08 21:47:27,938 db_split done                                                                         
[INFO] 2019-12-08 21:47:27,940 analysis tasks done                                                                   
[INFO] 2019-12-08 21:47:27,986 total jobs: 10                                                                        
[INFO] 2019-12-08 21:47:27,987 Throw jobID:[36460] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chai
n/02.map.ref.sh.work/map_genome00/nextPolish.sh] in the local_cycle.                                                 
[INFO] 2019-12-08 21:47:28,489 Throw jobID:[36469] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chai
n/02.map.ref.sh.work/map_genome01/nextPolish.sh] in the local_cycle.                                                 
[INFO] 2019-12-08 21:47:28,991 Throw jobID:[36481] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chai
n/02.map.ref.sh.work/map_genome02/nextPolish.sh] in the local_cycle.                                                 
[INFO] 2019-12-08 21:47:29,494 Throw jobID:[36490] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chai
n/02.map.ref.sh.work/map_genome03/nextPolish.sh] in the local_cycle.                                                 
[INFO] 2019-12-08 21:47:29,996 Throw jobID:[36499] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chai
n/02.map.ref.sh.work/map_genome04/nextPolish.sh] in the local_cycle.                                                 
[INFO] 2019-12-08 21:47:30,499 Throw jobID:[36508] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chai
n/02.map.ref.sh.work/map_genome05/nextPolish.sh] in the local_cycle.                                                 
[INFO] 2019-12-08 21:47:31,002 Throw jobID:[36517] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chai
n/02.map.ref.sh.work/map_genome06/nextPolish.sh] in the local_cycle.                                                 
[INFO] 2019-12-08 21:47:31,504 Throw jobID:[36526] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chai
n/02.map.ref.sh.work/map_genome07/nextPolish.sh] in the local_cycle.                                                 
[INFO] 2019-12-08 21:47:32,007 Throw jobID:[36535] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chai
n/02.map.ref.sh.work/map_genome08/nextPolish.sh] in the local_cycle.                                                 
[INFO] 2019-12-08 21:47:32,509 Throw jobID:[36544] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chai
n/02.map.ref.sh.work/map_genome09/nextPolish.sh] in the local_cycle.                                                 
[INFO] 2019-12-08 22:55:03,556 align_genome done                                                                     
[INFO] 2019-12-08 22:55:03,628 analysis tasks done                                                                   
[INFO] 2019-12-08 22:55:03,685 total jobs: 1                                                                         
[INFO] 2019-12-08 22:55:03,686 Throw jobID:[14907] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chai
n/03.merge.bam.sh.work/merge_bam0/nextPolish.sh] in the local_cycle.                                                 
[INFO] 2019-12-09 00:00:50,573 merge_bam done
[INFO] 2019-12-09 00:00:50,637 analysis tasks done
[INFO] 2019-12-09 00:00:50,683 total jobs: 10
[INFO] 2019-12-09 00:00:50,684 Throw jobID:[5428] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chain
/04.polish.ref.sh.work/polish_genome00/nextPolish.sh] in the local_cycle.
[INFO] 2019-12-09 00:00:51,186 Throw jobID:[5434] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chain
/04.polish.ref.sh.work/polish_genome01/nextPolish.sh] in the local_cycle.
[INFO] 2019-12-09 00:00:51,689 Throw jobID:[5440] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chain
/04.polish.ref.sh.work/polish_genome02/nextPolish.sh] in the local_cycle.
[INFO] 2019-12-09 00:00:52,191 Throw jobID:[5446] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome03/nextPolish.sh] in the local_cycle.
[INFO] 2019-12-09 00:00:52,694 Throw jobID:[5453] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome04/nextPolish.sh] in the local_cycle.
[INFO] 2019-12-09 00:00:53,196 Throw jobID:[5459] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome05/nextPolish.sh] in the local_cycle.
[INFO] 2019-12-09 00:00:53,699 Throw jobID:[5465] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome06/nextPolish.sh] in the local_cycle.
[INFO] 2019-12-09 00:00:54,201 Throw jobID:[5471] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome07/nextPolish.sh] in the local_cycle.
[INFO] 2019-12-09 00:00:54,704 Throw jobID:[5477] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome08/nextPolish.sh] in the local_cycle.
[INFO] 2019-12-09 00:00:55,206 Throw jobID:[5483] jobCmd:[/data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome09/nextPolish.sh] in the local_cycle.
[ERROR] 2019-12-09 00:01:00,217 polish_genome failed: please check the following logs:
[ERROR] 2019-12-09 00:01:00,218 /data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome00/nextPolish.sh.e
[ERROR] 2019-12-09 00:01:00,283 /data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome01/nextPolish.sh.e
[ERROR] 2019-12-09 00:01:00,283 /data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome02/nextPolish.sh.e
[ERROR] 2019-12-09 00:01:00,283 /data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome03/nextPolish.sh.e
[ERROR] 2019-12-09 00:01:00,284 /data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome04/nextPolish.sh.e
[ERROR] 2019-12-09 00:01:00,284 /data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome05/nextPolish.sh.e
[ERROR] 2019-12-09 00:01:00,284 /data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome06/nextPolish.sh.e
[ERROR] 2019-12-09 00:01:00,284 /data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome07/nextPolish.sh.e
[ERROR] 2019-12-09 00:01:00,284 /data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome08/nextPolish.sh.e
[ERROR] 2019-12-09 00:01:00,284 /data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome09/nextPolish.sh.e
```
Tail of the error:
```
(base) berombau@agro:/data/dp1/public/output/nextpolish$ tail /data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome09/nextPolish.sh.e
[INFO] 2019-12-09 00:00:55,274 Namespace(bam_lgs='/data/dp1/public/output/nextpolish/./01_rundir/00.score_chain/lgs.sort.bam', bam_sgs='/data/dp1/public/output/nextpolish/./01_rundir/00.score_chain/sgs.sort.bam', block='/data/dp1/public/output/nextpolish/./01_rundir/00.score_chain/input.genome.fasta.blc', block_index='9', count_read_ins_sgs=10000, debug=False, ext_len_edge=2, genome='/data/dp1/public/output/nextpolish/./01_rundir/00.score_chain/input.genome.fasta', indel_balance_factor_lgs=0.33, indel_balance_factor_sgs=0.5, max_clip_ratio_lgs=0.4, max_clip_ratio_sgs=0.15, max_count_kmer=50, max_indel_factor_lgs=0.21, max_ins_fold_sgs=5, max_ins_len_sgs=10000, max_len_kmer=50, max_snp_factor_lgs=0.53, max_variant_count_lgs=150000, min_count_ratio_skip=0.8, min_count_snp=5, min_count_snp_link=5, min_depth_snp=3, min_len_inter_kmer=5, min_len_ldr=3, min_map_quality=0, min_snp_factor_sgs=0.34, out='genome.nextpolish.part009.fasta', ploidy=2, process=2, task=1, trim_len_edge=2)
Traceback (most recent call last):
  File "/data/dp1/local/NextPolish/lib/nextPolish.py", line 331, in <module>
    main(args)
  File "/data/dp1/local/NextPolish/lib/nextPolish.py", line 216, in main
    CFG = P.config_init(args.genome, args.bam_sgs, args.bam_lgs)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
Command exited with non-zero status 1
0.05user 0.01system 0:00.07elapsed 98%CPU (0avgtext+0avgdata 12704maxresident)k
0inputs+0outputs (0major+1911minor)pagefaults 0swaps
```

**Comment by moold** [comment]
Could you check the input files of subtask: /data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome00/nextPolish.sh are existed and right?

**Comment by berombau** [comment]
After the make installation, I changed the hashbang of the nextPolish executable to `/data/dp1/local/miniconda3/envs/nextpolish/bin/python`
It points to a Python environment created with:
```
conda create -n nextpolish python=2.7 psutil
```
```
(nextpolish) berombau@agro:/data/dp1/public/short-reads$ /data/dp1/local/miniconda3/envs/nextpolish/bin/python --version
Python 2.7.15
(nextpolish) berombau@agro:/data/dp1/public/short-reads$ conda list
# packages in environment at /data/dp1/local/miniconda3/envs/nextpolish:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py27_0    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                hdf63c60_0    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pip                       19.3.1                   py27_0    conda-forge
psutil                    5.6.7            py27h516909a_0    conda-forge
python                    2.7.15            h5a48372_1009    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                42.0.2                   py27_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
wheel                     0.33.6                   py27_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

**Comment by moold** [comment]
May be you need change the `python` in /data/dp1/public/output/nextpolish/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome00/nextPolish.sh to `/data/dp1/local/miniconda3/envs/nextpolish/bin/python`, or add `/data/dp1/local/miniconda3/envs/nextpolish/bin/python` to your environment, so when you run `python`, it call the `/data/dp1/local/miniconda3/envs/nextpolish/bin/python`.

**Comment by berombau** [comment]
An incorrect version of python was indeed the problem. I solved my error by activating the conda environment and executing the unaltered executable with python directly: 
```
conda activate nextpolish
python {path_to_nextPolish} run.cfg
```
Thank you for your help!
