### ISSUE TITLE
After I run nextPolish run.cfg, the NextPolish vanished and generate a copy

### ISSUE THREAD

**Issue by SoSongzhi** [Nextomics/NextPolish#135]
Hi, I tried to polish a virus genome(hiv) with a single end long read file and a genome, the NextPolish folder only have one single file called 00.score_chain and It shows like that:
(base) zhi@zhi-ThinkStation-P360-Tower:~/Desktop/NextPolish$ ./nextPolish run.cfg 
[77443 INFO] 2024-08-28 16:24:16 NextPolish start...
[77443 INFO] 2024-08-28 16:24:16 version:v1.4.1 logfile:pid77443.log.info
[77443 WARNING] 2024-08-28 16:24:16 Delete task: 5 due to missing lgs_fofn.
[77443 WARNING] 2024-08-28 16:24:16 Delete task: 5 due to missing lgs_fofn.
[77443 WARNING] 2024-08-28 16:24:16 Delete task: 6 due to missing hifi_fofn.
[77443 WARNING] 2024-08-28 16:24:16 Delete task: 6 due to missing hifi_fofn.
[77443 INFO] 2024-08-28 16:24:16 scheduled tasks:
[1, 2, 1, 2]
[77443 INFO] 2024-08-28 16:24:16 options: 
[77443 INFO] 2024-08-28 16:24:16 
rerun:                        3
rewrite:                      0
kill:                         None
cleantmp:                     0
use_drmaa:                    0
submit:                       None
deltmp:                       False
job_type:                     local
sgs_unpaired:                 0
sgs_rm_nread:                 1
lgs_read_type:                
parallel_jobs:                6
align_threads:                5
check_alive:                  None
task:                         [1, 2, 1, 2]
job_id_regex:                 None
sgs_max_depth:                100
lgs_max_depth:                100
multithread_jobs:             5
genome_size:                  492264
lgs_max_read_len:             0
hifi_max_depth:               100
lgs_block_size:               500M
lgs_min_read_len:             1k
hifi_max_read_len:            0
polish_options:               -p 5
hifi_block_size:              500M
hifi_min_read_len:            1k
job_prefix:                   nextPolish
sgs_block_size:               8204400.0
sgs_use_duplicate_reads:      0
lgs_minimap2_options:         -x map-ont
hifi_minimap2_options:        -x map-pb
sgs_align_options:            bwa mem -p  -t 5
workdir:                      /home/zhi/Desktop/NextPolish
sgs_fofn:                     /home/zhi/Desktop/NextPolish/sgs.fofn
genome:                       /home/zhi/Desktop/NextPolish/50x_6k_raw.fa
snp_phase:                    /home/zhi/Desktop/NextPolish/%02d.snp_phase
snp_valid:                    /home/zhi/Desktop/NextPolish/%02d.snp_valid
lgs_polish:                   /home/zhi/Desktop/NextPolish/%02d.lgs_polish
kmer_count:                   /home/zhi/Desktop/NextPolish/%02d.kmer_count
hifi_polish:                  /home/zhi/Desktop/NextPolish/%02d.hifi_polish
score_chain:                  /home/zhi/Desktop/NextPolish/%02d.score_chain
[77443 WARNING] 2024-08-28 16:24:16 mv /home/zhi/Desktop/NextPolish to /home/zhi/Desktop/NextPolish.backup0
[77443 INFO] 2024-08-28 16:24:16 step 0 and task 1 start:
[77443 INFO] 2024-08-28 16:24:21 Total jobs: 3
[77443 INFO] 2024-08-28 16:24:21 Submitted jobID:[77480] jobCmd:[/home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh] in the local_cycle.
[77480 CRITICAL] 2024-08-28 16:24:21 Command '/bin/bash /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh > /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh.o 2> /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh.e' returned non-zero exit status 127, error info: .
Traceback (most recent call last):
  File "/home/zhi/Desktop/NextPolish/./nextPolish", line 553, in <module>
  File "/home/zhi/Desktop/NextPolish/./nextPolish", line 403, in main
  File "/home/zhi/anaconda3/lib/python3.11/site-packages/paralleltask/task_control.py", line 350, in start
    self._start()
  File "/home/zhi/anaconda3/lib/python3.11/site-packages/paralleltask/task_control.py", line 376, in _start
    self.submit(job)
  File "/home/zhi/anaconda3/lib/python3.11/site-packages/paralleltask/task_control.py", line 254, in submit
    _, stdout, _ = self.run(job.cmd)
                   ^^^^^^^^^^^^^^^^^
  File "/home/zhi/anaconda3/lib/python3.11/site-packages/paralleltask/task_control.py", line 294, in run
    log.critical("Command '%s' returned non-zero exit status %d, error info: %s." % (cmd, p.returncode, stderr))
  File "/home/zhi/anaconda3/lib/python3.11/logging/__init__.py", line 1536, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/home/zhi/anaconda3/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/home/zhi/anaconda3/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/home/zhi/anaconda3/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/home/zhi/anaconda3/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/home/zhi/anaconda3/lib/python3.11/site-packages/paralleltask/kit.py", line 42, in emit
    raise Exception(record.msg)
Exception: Command '/bin/bash /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh > /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh.o 2> /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh.e' returned non-zero exit status 127, error info: .
[77443 INFO] 2024-08-28 16:24:22 Submitted jobID:[77487] jobCmd:[/home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split2/nextPolish.sh] in the local_cycle.
[77487 CRITICAL] 2024-08-28 16:24:22 Command '/bin/bash /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split2/nextPolish.sh > /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split2/nextPolish.sh.o 2> /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split2/nextPolish.sh.e' returned non-zero exit status 127, error info: .
Traceback (most recent call last):
  File "/home/zhi/Desktop/NextPolish/./nextPolish", line 553, in <module>
  File "/home/zhi/Desktop/NextPolish/./nextPolish", line 403, in main
  File "/home/zhi/anaconda3/lib/python3.11/site-packages/paralleltask/task_control.py", line 350, in start
    self._start()
  File "/home/zhi/anaconda3/lib/python3.11/site-packages/paralleltask/task_control.py", line 376, in _start
    self.submit(job)
  File "/home/zhi/anaconda3/lib/python3.11/site-packages/paralleltask/task_control.py", line 254, in submit
    _, stdout, _ = self.run(job.cmd)
                   ^^^^^^^^^^^^^^^^^
  File "/home/zhi/anaconda3/lib/python3.11/site-packages/paralleltask/task_control.py", line 294, in run
    log.critical("Command '%s' returned non-zero exit status %d, error info: %s." % (cmd, p.returncode, stderr))
  File "/home/zhi/anaconda3/lib/python3.11/logging/__init__.py", line 1536, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/home/zhi/anaconda3/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/home/zhi/anaconda3/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/home/zhi/anaconda3/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/home/zhi/anaconda3/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/home/zhi/anaconda3/lib/python3.11/site-packages/paralleltask/kit.py", line 42, in emit
    raise Exception(record.msg)
Exception: Command '/bin/bash /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split2/nextPolish.sh > /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split2/nextPolish.sh.o 2> /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split2/nextPolish.sh.e' returned non-zero exit status 127, error info: .
[77443 INFO] 2024-08-28 16:24:22 Submitted jobID:[77503] jobCmd:[/home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split3/nextPolish.sh] in the local_cycle.
[77503 CRITICAL] 2024-08-28 16:24:22 Command '/bin/bash /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split3/nextPolish.sh > /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split3/nextPolish.sh.o 2> /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split3/nextPolish.sh.e' returned non-zero exit status 127, error info: .
Traceback (most recent call last):
  File "/home/zhi/Desktop/NextPolish/./nextPolish", line 553, in <module>
  File "/home/zhi/Desktop/NextPolish/./nextPolish", line 403, in main
  File "/home/zhi/anaconda3/lib/python3.11/site-packages/paralleltask/task_control.py", line 350, in start
    self._start()
  File "/home/zhi/anaconda3/lib/python3.11/site-packages/paralleltask/task_control.py", line 376, in _start
    self.submit(job)
  File "/home/zhi/anaconda3/lib/python3.11/site-packages/paralleltask/task_control.py", line 254, in submit
    _, stdout, _ = self.run(job.cmd)
                   ^^^^^^^^^^^^^^^^^
  File "/home/zhi/anaconda3/lib/python3.11/site-packages/paralleltask/task_control.py", line 294, in run
    log.critical("Command '%s' returned non-zero exit status %d, error info: %s." % (cmd, p.returncode, stderr))
  File "/home/zhi/anaconda3/lib/python3.11/logging/__init__.py", line 1536, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/home/zhi/anaconda3/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/home/zhi/anaconda3/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/home/zhi/anaconda3/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/home/zhi/anaconda3/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/home/zhi/anaconda3/lib/python3.11/site-packages/paralleltask/kit.py", line 42, in emit
    raise Exception(record.msg)
Exception: Command '/bin/bash /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split3/nextPolish.sh > /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split3/nextPolish.sh.o 2> /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split3/nextPolish.sh.e' returned non-zero exit status 127, error info: .
[77443 ERROR] 2024-08-28 16:24:29 db_split failed: please check the following logs:
[77443 ERROR] 2024-08-28 16:24:29 /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh.e
[77443 ERROR] 2024-08-28 16:24:29 /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split2/nextPolish.sh.e
[77443 ERROR] 2024-08-28 16:24:29 /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split3/nextPolish.sh.e

Could you please help me to check where should I do to due with this problem. Thx.

**Comment by SoSongzhi** [comment]
And the nextPolish.sh.e file shows like that:
hostname
+ hostname
cd /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split1
+ cd /home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split1
( time  /home/zhi/Desktop/NextPolish/bin/seq_split -d /home/zhi/Desktop/NextPolish -m 8204400.0 -n 6 -t 5 -i 1 -s 49226400 -p input.sgspart /home/zhi/Desktop/NextPolish/sgs.fofn )
+ /home/zhi/Desktop/NextPolish/bin/seq_split -d /home/zhi/Desktop/NextPolish -m 8204400.0 -n 6 -t 5 -i 1 -s 49226400 -p input.sgspart /home/zhi/Desktop/NextPolish/sgs.fofn
/home/zhi/Desktop/NextPolish/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh: line 5: /home/zhi/Desktop/NextPolish/bin/seq_split: No such file or directory

real	0m0.001s
user	0m0.001s
sys	0m0.001s



but it was all good when I use the test data provided by the source.

**Comment by moold** [comment]
seet `rewrite=yes`
