### ISSUE TITLE
Maybe a small bug?

### ISSUE THREAD

**Issue by awesomedeer** [Nextomics/NextPolish#34]
Hi!
Thanks for maintaining NextPolish.
I think it's just a small issue below when I try to use NGS-data to polish:
**Error message**
<pre>
Traceback (most recent call last):
  File "/public/home/wusong/sfw/NextPolish/nextPolish", line 460, in <module>
    main(args)
  File "/public/home/wusong/sfw/NextPolish/nextPolish", line 358, in main
    task = Task(set_task(cfg, 'map_genome', path = path, genomefile = genomefile, gtask = gtask), prefix = 'map_genome', convertpath = False)
  File "/public/home/wusong/sfw/NextPolish/nextPolish", line 33, in set_task
    cmd = map_genome(cfg, genomefile = args['genomefile'], task = args['gtask'])
  File "/public/home/wusong/sfw/NextPolish/nextPolish", line 144, in map_genome
    THREADS = str(cfg['align_threads']) if cfg['align_threads'] < 5 else '5'
TypeError: '<' not supported between instances of 'str' and 'int'

</pre>

I am using NextPolish 1.2.4.
The code is modified to
`THREADS = str(cfg['align_threads']) if int(cfg['align_threads']) < 5 else '5'`
and it works.
Not so sure whether it's caused by the requirements or something else.

Best wishes
Song

**Comment by moold** [comment]
Yes, it is a bug, and thank you for your report. I will fix it in the next release.
