### ISSUE TITLE
error with test data

### ISSUE THREAD

**Issue by jforero2020** [Nextomics/NextPolish#51]
Hello, 
I try to run the test, I got this error

```
+ time /datos/datosjforero/miniconda3/envs/rompecabezas/bin/python /datos/datosjforero/tutoriales/anaconda3/NextPolish/lib/nextpolish2.py -sp -p 3 -g /datos/datosjforero/tutoriales/anaconda3/NextPolish/test_data/./01_rundir/00.lgs_polish/input.genome.fasta -b /datos/datosjforero/tutoriales/anaconda3/NextPolish/test_data/./01_rundir/00.lgs_polish/input.genome.fasta.blc -i 0 -l /datos/datosjforero/tutoriales/anaconda3/NextPolish/test_data/./01_rundir/00.lgs_polish/lgs.sort.bam.list -r ont -o genome.nextpolish.part000.fasta
Traceback (most recent call last):
  File "/datos/datosjforero/tutoriales/anaconda3/NextPolish/lib/nextpolish2.py", line 54, in <module>
    P = CDLL(os.path.dirname(os.path.realpath(__file__)) + '/' + "nextpolish2.so")
  File "/datos/datosjforero/miniconda3/envs/rompecabezas/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
**OSError: liblzma.so.0: cannot open shared object file: No such file or directory**
Command exited with non-zero status 1
0.03user 0.00system 0:00.03elapsed 97%CPU (0avgtext+0avgdata 12332maxresident)k
0inputs+0outputs (0major+1895minor)pagefaults 0swaps
```
I am using Ubuntu 18.04.5 
Nextpolish version: v1.3.0
Python version: 3.7.6

Thanks for your help ;).

**Comment by moold** [comment]
Could you try to download another version, its link is list in the download section.

**Comment by jforero2020** [comment]
It worked!!!!! Thank you 👍
