### ISSUE TITLE
nextPolish on Docker

### ISSUE THREAD

**Issue by marco91sol** [Nextomics/NextPolish#67]
**Describe the bug**
Hi, 

I ran nextPolish on docker. Firstly, I used the docker pull pvstodghill/nextpolish. 
Later, I ran the following command: 
 docker run --ulimit nofile=64000:64000 -u $(id -u) -v /mnt/mrc/CS:/nextPolish_wd pvstodghill/nextpolish nextPolish ./run.cfg.nextpolish 

**Error message**
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Traceback (most recent call last):
  File "/opt/NextPolish/nextPolish", line 511, in <module>
    main(args)
  File "/opt/NextPolish/nextPolish", line 337, in main
    log = plog(log_file)
  File "/opt/NextPolish/lib/kit.py", line 56, in plog
    fileHandler = logging.FileHandler(path, mode='w')
  File "/usr/lib/python2.7/logging/__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/mnt/pid1.log.info'

How can I solve this issue?

**Comment by moold** [comment]
Hi, I do not familiar with docker, so you can follow [here](https://nextpolish.readthedocs.io/en/latest/QSTART.html#installation) to have a try.
